### ISSUE TITLE
AttributeError: module 'models' has no attribute 'CSS_DDI'

### ISSUE THREAD

**Issue by drunkprogrammer** [microsoft/IGT-Intermolecular-Graph-Transformer#4]
In your Drug-Interaction-Research project:

There is no CSS-DDI model in your models.py file.

![DSN-DDI error](https://user-images.githubusercontent.com/19500408/236617345-b5840add-c3de-4b73-ba63-a980f0212ab5.png)

**Comment by ElwynWang** [comment]
bug fixed

**Comment by Godzshaoshuai** [comment]
可以公布吗
