### ISSUE TITLE
Wondering how to use attention scores to paint important atoms

### ISSUE THREAD

**Issue by Ngqgq** [microsoft/IGT-Intermolecular-Graph-Transformer#5]
I would like to know how to do this, if possible, could you provide a method to achieve drawing this graph? This means a lot to me, thank you very much.

![image](https://user-images.githubusercontent.com/87457554/236622726-22ed9973-60e2-4c10-b9e8-15fbcf6a6bcb.png)

**Comment by ElwynWang** [comment]
1. Get the attention score from model. 
2. Use RDKit to output the indices of atoms.
3. Label the atoms with highest att score manully
