### ISSUE TITLE
ERROR 409: Public access is not permitted on this storage account

### ISSUE THREAD

**Issue by forward-zhang** [microsoft/IGT-Intermolecular-Graph-Transformer#6]
I tried wget https://msracb.blob.core.windows.net/pub/DSN-DDI-dataset.zip
it returned ERROR 409: Public access is not permitted on this storage account..

**Comment by shineonme56** [comment]
same error occurs. how do i access?

**Comment by kks6482** [comment]
same error occurs. how do i access?

**Comment by forward-zhang** [comment]
(T _T)

**Comment by ElwynWang** [comment]
already uploaded dataset in the code repo
